# To execute this docker-compose yml file use 'docker-compose -f docker-compose-v3.yml up'
# Add the '-d' flag at the end for the detached execution
# To stop the execution, hit CTRL+C, and then 'docker-compose -f docker-compose-v3.yml down'
version: "3"
services:
  jaegar:
    image: jaegertracing/all-in-one:1.17
    ports:
      - "16686:16686"
      - "14250:14250"
  chrome:
    image: selenium/node-chrome:4.10.0-20230607
    privileged: true
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
      - SE_NODE_MAX_INSTANCES=3
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_ENABLE_TRACING=true
      - JAVA_OPTS=-Dotel.traces.exporter=jaeger -Dotel.exporter.jaeger.endpoint=http://jaegar:14250 -Dotel.resource.attributes=service.name=selenium-node-chrome
      - SE_VNC_NO_PASSWORD=1
#      - SE_OPTS=--log-level FINE
    ports:
      - "6900:5900"

  chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20230508
    volumes:
      - ./videos:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_video.mp4

  edge:
    image: selenium/node-edge:4.10.0-20230607
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
      - SE_NODE_MAX_INSTANCES=3
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_ENABLE_TRACING=true
      - JAVA_OPTS=-Dotel.traces.exporter=jaeger -Dotel.exporter.jaeger.endpoint=http://jaegar:14250 -Dotel.resource.attributes=service.name=selenium-node-chrome
      - SE_VNC_NO_PASSWORD=1
    ports:
        - "6901:5900"

  firefox:
    image: selenium/node-firefox:4.10.0-20230607
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
      - SE_NODE_MAX_INSTANCES=3
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_ENABLE_TRACING=true
      - JAVA_OPTS=-Dotel.traces.exporter=jaeger -Dotel.exporter.jaeger.endpoint=http://jaegar:14250 -Dotel.resource.attributes=service.name=selenium-node-chrome
      - SE_VNC_NO_PASSWORD=1
#      - SE_OPTS=--log-level FINE
    ports:
      - "6902:5900"

  selenium-hub:
    image: selenium/hub:4.10.0-20230607
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    depends_on:
      - jaegar
    environment:
      - SE_ENABLE_TRACING=true
      - JAVA_OPTS=-Dotel.traces.exporter=jaeger -Dotel.exporter.jaeger.endpoint=http://jaegar:14250 -Dotel.resource.attributes=service.name=selenium-hub
#      - SE_OPTS=--log-level FINE

  uitest-module:
    image: deepkandey/uitestautomation:latest
    depends_on:
      - chrome
      - firefox
#      - edge
    environment:
      - HUB_HOST=selenium-hub
    volumes:
      - ./test-result-extent:/usr/share/UITestAutomationFramework/test-output

# MaxInstances applies to a specific browser, while MaxSessions applies to the entire node.