# To execute this docker-compose yml file use 'docker-compose -f docker-compose-v3.yml up'
# Add the '-d' flag at the end for the detached execution
# To stop the execution, hit CTRL+C, and then 'docker-compose -f docker-compose-v3.yml down'
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.8.1-20230221
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
      - SE_NODE_MAX_INSTANCES=4
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    ports:
      - "6900:5900"

  edge:
    image: selenium/node-edge:4.8.1-20230221
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
      - SE_NODE_MAX_INSTANCES=4
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    ports:
      - "6901:5900"

  firefox:
    image: selenium/node-firefox:4.8.1-20230221
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444
      - SE_NODE_MAX_INSTANCES=4
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    ports:
      - "6902:5900"

  selenium-hub:
    image: selenium/hub:4.8.1-20230221
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  uitest-module:
    image: deepkandey/uitestautomation:latest
    depends_on:
      - chrome
      - firefox
      - edge
    environment:
      - HUB_HOST=selenium-hub
    volumes:
      - ./test-result-extent:/usr/share/UITestAutomationFramework/test-output
